import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import TicketProvider from "@/context/TicketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ticket App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TicketProvider>
          <div className="bg-sky-900 pb-32 min-h-screen">
            <Navbar />
            {children}
          </div>
        </TicketProvider>
      </body>
    </html>
  );
}
